language: android

before_install:
    - mvn install:install-file -DgroupId=com.google.android.maps -DartifactId=maps -Dversion=18_r3 -Dpackaging=jar -Dfile="$ANDROID_HOME/add-ons/addon-google_apis-google-18/libs/maps.jar"
    - mvn install:install-file -DgroupId=com.android.support -DartifactId=support-v4 -Dversion=19.0.1 Dpackaging=jar Dfile="$ANDROID_HOME/extras/android/m2repository/com/android/support/support-v4/19.0.1/support-v4-19.0.1.jar"

android:
  components:

    # The BuildTools version used by your project
    - build-tools-19.1.0

    # The SDK version used to compile your project
    - android-19

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-18
